### ISSUE TITLE
Handmade styled menu points should be automatically centered

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/nucleoid-extras#116]
Currently, handmade styled menus are defined by exact points with the slots available:

https://github.com/NucleoidMC/Game-Configs/blob/bcc4a1e1c36f57678b7b28bf35452aa42c23120b/data/nucleoid/game_portals/top_level/destroy_the_monument_modes.json#L8-L19

Ideally, the points wouldn't have to conform to a given size and automatically center themselves while keeping their internal layout. For example, three entries laid out horizontally could be specified as `0:0`, `1:0`, and `2:0` or `4:3`, `5:3`, and `6:3`.

**Comment by Patbox** [comment]
This allows it to be more flexible than if it was always centered. It's intended
