### ISSUE TITLE
Selecting 'View All Games' in the navigator does not return to the top level

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/nucleoid-extras#117]
When selecting a nested menu from the top level of the navigator, selecting 'View Open Games', and then 'View All Games', the nested menu will be displayed rather than the top level of the navigator. This is slightly confusing and would potentially allow quick access to the top level if #118 is not implemented.

**Comment by Patbox** [comment]
Intended, but might change lang files tbf
