### ISSUE TITLE
Dice taters roll too quickly

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/nucleoid-extras#75]
As of 58acbdb297af5065f99e0ff5f8390ad40b74b07a, dice taters immediately roll then switch to a new value rather than rolling for a few ticks before switching to a new value. This is likely caused by the tick being scheduled incorrectly:

https://github.com/NucleoidMC/nucleoid-extras/blob/96771a7e7ba5a68aee8fc70e8fc44b9651d1a273/src/main/java/xyz/nucleoid/extras/lobby/block/DiceTaterBlock.java#L55

**Comment by Shnupbups** [comment]
This issue has been fixed and can be closed
